### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by dijs** [rzimmerman/kal#100]
Could this ever be a thing in Kal?

```
test = "#{2 + 2}"
# where test would equal "4"
```

Obviously, it would be great to use variables also...

**Comment by dijs** [comment]
This is from Douglas Crawford's "Remedial Javascript". I thought I might help.

```
String.prototype.supplant = function (o) {
    return this.replace(/{([^{}]*)}/g,
        function (a, b) {
            var r = o[b];
            return typeof r === 'string' || typeof r === 'number' ? r : a;
        }
    );
};
// Usage:
alert("I'm {age} years old!".supplant({ age: 29 }));
alert("The {a} says {n}, {n}, {n}!".supplant({ a: 'cow', n: 'moo' }));
```

I thought this was a clean way to approach the problem.

**Comment by rzimmerman** [comment]
If I'm understanding you correctly, you're looking for string syntax like:

``` kal
s = "I am #{50+1} years old"
```

Which is already supported. The `supplant` thing is not supported right now (kind of like Python's old `%` operator?), although you could do:

``` kal
a = cow
n = moo
print "The #{a} says #{n}, #{n}, #{n}!"
```

**Comment by rzimmerman** [comment]
Also, it only works with double quoted strings, not single quoted strings (on purpose like CoffeeScript).

**Comment by dijs** [comment]
_Facepalm_ I had no idea this was already supported... 

Is it in your documentation?

**Comment by rzimmerman** [comment]
Technically yes, but it's just one little line in the readme (I agree it's not obvious at all). I'll add something more substantive.
