### ISSUE TITLE
Does `is not` equal to `isnt`

### ISSUE THREAD

**Issue by bcho** [rzimmerman/kal#112]
The code likes that:

``` kal
x = 'foo' if y is not null else 'bar'
```

will generate this js code:

``` javascript
x = (y === !null) ? 'foo' : 'bar';
```

but actually what I want is:

``` javascript
x = (y !== null) ? 'foo' : 'bar';
```

And the second generated code is exactlly what `isnt` generated.

So, does `is not` not equal to `isnt` ?

**Comment by rzimmerman** [comment]
I agree this is confusing. "is not" should be equivalent to "isnt" (I'll work it in). "doesnt exist" works well for null checks at the moment.
