### ISSUE TITLE
node.js' require not working

### ISSUE THREAD

**Issue by jeancarlozapata** [rzimmerman/kal#120]
Using a `require` from a simple script like this:

```
fs = require 'fs'

root = '/home/caramba/Desktop'

wait for files from fs.readdir root

for file in files
  print root + file
```

Throws an error `require is not defined`:

```
/home/caramba/npm/lib/node_modules/kal/compiled/kal.js:1
rts.makeSandbox(options):options.sandbox:global,sandbox===global?vm.runInThisC
                                                                    ^
ReferenceError: require is not defined
    at evalmachine.<anonymous>:4:8
    at evalmachine.<anonymous>:15:6
    at Object.kal_eval [as eval] (/home/caramba/npm/lib/node_modules/kal/compiled/kal.js:1:830)
    at Object.run (/home/caramba/npm/lib/node_modules/kal/compiled/command.js:1:2421)
    at Object.<anonymous> (/home/caramba/npm/lib/node_modules/kal/scripts/kal:7:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Using:**
node v0.10.19 (installed on /usr/bin/node)
npm v1.3.11(installed on /usr/bin/npm)
Kal version 0.5.4 (installed on /home/caramba/npm/bin/kal)
Ubuntu 13.04

If you need more info about the issue please let me know

**EDIT:** even a simple file with just a valid require line

```
path = require 'path'
```

fails throwing the same error about `require is not defined`

**EDIT 2:** I configure `npm` according to this https://github.com/isaacs/npm/issues/3139#issuecomment-13360417 to avoid installing stuff using sudo (`npm install -g somepackage` instead of `sudo npm install -g somepackage`).

**Comment by rzimmerman** [comment]
@jeancarlozapata thanks for reporting this. It looks like things broke when I transferred over to the literate source. I must have taken this line out without checking.

I'm going to release 0.5.5 to fix this in a few minutes.

**Comment by jeancarlozapata** [comment]
:+1: Great, glad I was helpful. Keep up the great work!

**Comment by rzimmerman** [comment]
It's out on npm now.
