### ISSUE TITLE
Minor documentation error in "Loops" section of readme.md

### ISSUE THREAD

**Issue by pojala** [rzimmerman/kal#81]
On line 350 in README.md, the description of the iterant used in 'for' loops seems to be cut off:

_... The value n the right of the `for ... in` expression is called the `iterant`. It must either be an array._

Can the iterant be something else than an array?

**Comment by rzimmerman** [comment]
I was originally going to say:
_It must either be an array or an iterable object._

But then I realized iterables don't work in for `loops` yet, just in comprehensions.
