### ISSUE TITLE
add website to repository

### ISSUE THREAD

**Issue by optikfluffel** [rzimmerman/kal#86]
could you add the link to [the website](http://rzimmerman.github.io/kal/) to the repo? ^^

**Comment by rzimmerman** [comment]
You meant for the README file, right? Or is there somewhere else I'm missing a link?

**Comment by optikfluffel** [comment]
![Edit Link](http://f.cl.ly/items/452O3o192b3d0n3k3C1x/Screen%20Shot%202013-08-21%20at%2010.23.23.png)

you should be able to add it there ^^

**Comment by rzimmerman** [comment]
OK, I see it now. Thanks, I added it.
