### ISSUE TITLE
Modular Operator Broken

### ISSUE THREAD

**Issue by dijs** [rzimmerman/kal#91]
trying to compile: console.log(5 % 2)

Gives compiler error:

/usr/local/lib/node_modules/kal/compiled/kal.js:1
oad(parser.Grammar),root_node.js(options)}catch(e){throw e.message||e}}var sug
                                                                    ^
invalid token '% 2);...' on line 1

**Comment by cmwelsh** [comment]
Your issue is addressed by #90. There is no modulo operator yet.

**Comment by rzimmerman** [comment]
I merged in @mrshu's branch, so `mod` works now.
