### ISSUE TITLE
Callback functions not working...

### ISSUE THREAD

**Issue by dijs** [rzimmerman/kal#92]
Maybe I am just doing this wrong, but I could not find any good examples in your Readme...

```
square = (u) ->
    return u ^ 2

task myTask (u)
    setTimeout () ->
        return square u
    , 2000

wait for x from myTask 3
print x
```

Gives this error...

```
/usr/local/lib/node_modules/kal/compiled/kal.js:12
            throw e.message || e;
                               ^
Expected Statement on line 7
```

**Comment by rzimmerman** [comment]
This is actually documented in gh-38 as a known issue. Kal confuses the parentheses after `setTimeout` as a call to `setTimeout`. For now, you need extra parentheses, for example:

``` kal
square = (u) ->
    return u ^ 2

task myTask (u)
    setTimeout(( ->
        return square u
    ), 2000)

wait for x from myTask 3
print x
```

Also I'll probably add an alias for `setTimeout` soon because it's arguments are so backward.
