### ISSUE TITLE
Classes need to have tasks also

### ISSUE THREAD

**Issue by dijs** [rzimmerman/kal#98]
Is this easy to implement?

**Comment by rzimmerman** [comment]
For some reason I thought this worked already. I'll put it on the list to make sure it does.

**Comment by rzimmerman** [comment]
I checked - it looks like these are not compiling as expected:

``` kal
class ABC
  task d()
    return 1
```

Compiles to 

``` javascript
function ABC() {
}

ABC.d = function (k$next) {
  var k$rv;
  try {
    return k$rv = [null, 1], k$next.apply(this, k$rv);
  } catch (k$err) {if (k$next) {return k$next.apply(this,[k$err]);} else {throw k$err;}}
  return k$next ? k$next() : void 0;
}
```

It should be assigning to `ABC.prototype.d`.

**Comment by dijs** [comment]
Yep, thats what I got too.

Should be an easy fix though. :)
